DROP TABLE IF EXISTS salle;
CREATE TABLE salle (
nom TEXT PRIMARY KEY,
resourceID INTEGER UNIQUE DEFAULT NULL,
type TEXT,
taille INTEGER NOT NULL DEFAULT 0,
projecteur INTEGER NOT NULL DEFAULT 0,
tableau INTEGER NOT NULL DEFAULT 0,
imprimante INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS prof;
CREATE TABLE prof (
nom TEXT PRIMARY KEY,
resourceID INTEGER UNIQUE DEFAULT NULL,
bureau TEXT DEFAULT NULL,
email TEXT DEFAULT NULL
);
